### ISSUE TITLE
Using custom Object detection Model of YOLO?

### ISSUE THREAD

**Issue by avinashnair02** [grebtsew/Realtime-Screen-Object-Detection#3]
Can this be used for object detection using YOLOV5 model?

**Comment by grebtsew** [comment]
Hello @avinashnair02,

Yes, changing models should actually be quite straight forward.

The only file that would need edit is ./detection.py.

Specifically update path to model file, the load_modell method and needed convertions, depending on the model for prediction in the run method.

Cheers, 
@grebtsew

**Comment by grebtsew** [comment]
Hello @avinashnair02,

From commit #a01c34b that i pushed today, the implementation seems to work with Yolov8 or Yolov5. For that reason I am now closing this issue. There are still a couple of fixed to be added to the project before a release.

Cheers,
@grebtsew
